<?php

namespace ipezbo\MailSettingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MailSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailSettingRepository extends EntityRepository
{
}
