parameters:
#    ipezbo_customer.example.class: ipezbo\CustomerBundle\Example

services:
#    ipezbo_customer.example:
#        class: %ipezbo_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
