ipezbo_brand_homepage:
    pattern:  /
    defaults: { _controller: ipezboBrandBundle:Brand:index }

ipezbo_brand_add:
    pattern:  /add
    defaults: { _controller: ipezboBrandBundle:Brand:add }

ipezbo_brand_edit:
    pattern:  /edit/{id}
    defaults: { _controller: ipezboBrandBundle:Brand:edit }
    requirements:
        id : \d+