parameters:
#    ipezbo_general_setting.example.class: ipezbo\GeneralSettingBundle\Example

services:
#    ipezbo_general_setting.example:
#        class: %ipezbo_general_setting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
