<?php

namespace ipezbo\VisitorNewsletterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitorNewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorNewsletterRepository extends EntityRepository
{
}
