ipezbo_alert_homepage:
    pattern:  /
    defaults: { _controller: ipezboAlertBundle:Alert:index }

ipezbo_alert_delete:
    pattern:  /delete/{id}
    defaults: { _controller: ipezboAlertBundle:Alert:delete }
    requirements :
        id : \d+