parameters:
#    ipezbo_alert.example.class: ipezbo\AlertBundle\Example

services:
#    ipezbo_alert.example:
#        class: %ipezbo_alert.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
