parameters:
#    ipezbo_mail_setting.example.class: ipezbo\MailSettingBundle\Example

services:
#    ipezbo_mail_setting.example:
#        class: %ipezbo_mail_setting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
