<?php

namespace ipezbo\GeneralSettingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeneralSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralSettingRepository extends EntityRepository
{
}
