ipezbo_product_homepage:
    pattern:  /
    defaults: { _controller: ipezboProductBundle:Product:index }

ipezbo_product_add:
    pattern:  /add
    defaults: { _controller: ipezboProductBundle:Product:add }

ipezbo_product_edit:
    pattern:  /edit/{id}
    defaults: { _controller: ipezboProductBundle:Product:edit }
    requirements:
        id : \d+

ipezbo_product_delete:
    pattern:  /delete/{id}
    defaults: { _controller: ipezboProductBundle:Product:delete }
    requirements :
        id : \d+