parameters:
#    ipezbo_product.example.class: ipezbo\ProductBundle\Example

services:
#    ipezbo_product.example:
#        class: %ipezbo_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
