ipezbo_visitor_newsletter_homepage:
    pattern:  /
    defaults: { _controller: ipezboVisitorNewsletterBundle:VisitorNewsletter:index }

ipezbo_visitor_newsletter_delete:
    pattern:  /delete/{id}
    defaults: { _controller: ipezboVisitorNewsletterBundle:VisitorNewsletter:delete }
    requirements :
        id : \d+