parameters:
#    ipezbo_event.example.class: ipezbo\EventBundle\Example

services:
#    ipezbo_event.example:
#        class: %ipezbo_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
