parameters:
#    ipezbo_participation.example.class: ipezbo\ParticipationBundle\Example

services:
#    ipezbo_participation.example:
#        class: %ipezbo_participation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
